### ISSUE TITLE
api请求报错了

### ISSUE THREAD

**Issue by mrbruce516** [fghrsh/live2d_api#7]
2020/4/29 晚上7点，请求api接口的时候报错了，
[Error] Failed to load resource: 此服务器的证书无效。您可能正在连接一个伪装成“live2d.fghrsh.net”的服务器，这会威胁到您的机密信息的安全。 (get, line 0)

**Comment by OldTaoge** [comment]
证书过期了，看来自己搭建API才是王道

**Comment by mrbruce516** [comment]
作者好像解决了，感谢作者！！！
